### ISSUE TITLE
Planned cuDNN v5 support?

### ISSUE THREAD

**Issue by phiber1** [denizyuret/CUDNN.jl#3]
Shouldn't be that hard to update. Ubuntu 16.04 has been at cuDNN v5 for a few weeks now...

**Comment by denizyuret** [comment]
Started working on this.  Should be ready in a few weeks.

**Comment by phiber1** [comment]
Excellent news!
Thanks,
Mark

**Comment by MikeInnes** [comment]
As part of #6 I got the tests passing with CUDA 6; I don't know if you want 5 specifically, but if CUDNN can find it then it should work OK.
