### ISSUE TITLE
Does CUDNN.jl support 2-D CudaArray's

### ISSUE THREAD

**Issue by AStupidBear** [denizyuret/CUDNN.jl#4]

**Comment by denizyuret** [comment]
Most operations in the original cudnn library support 4-D arrays (2 spatial dimensions + channel + minibatchSize).  Recently they have added 5-D support for 3-D convolution.  CUDNN.jl supports everything the cudnn library supports (please refer to the NVIDIA documentation for details), some CUDNN.jl ops may support lower dimensional arrays by padding them with singleton dimensions.
